config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  root 'pages#welcome'
  get 'about', to: 'pages#about'
  get 'json_data', to: 'pages#json_data'
  resources :articles
  resources :profiles, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10 }

  belongs_to :user

  scope :on_created_at, -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy

  validates :username, presence: true

  scope :on_created_at, -> { order(created_at: :asc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @page = (params[:page] || 0).to_i
    @articles = Article.on_created_at.offset(3 * @page).limit(3)
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.new(article_params)

    if @article.save
      flash[:notice] = "Article was successfully created"
      redirect_to @article
    else
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated"
      redirect_to article_path(@article)
    else
      flash[:notice] = "Article was not updated"
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = "Article was deleted"
    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :description)
    end

    def set_article
      @article = Article.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:welcome, :about, :json_data]

  def welcome; end

  def about; end

  def json_data
    cursor = (params[:cursor] || 0).to_i

    @users = User.where("id > ?", cursor).on_created_at

    render json: @users
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def index
    @page = (params[:page] || 0).to_i
    @users = User.on_created_at.offset(3 * @page).limit(3)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def gravatar_for(user, options = { size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/views/articles/_article.html.erb
<% resources.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= raw(article.description).truncate(100).html_safe %>
          <p>
            Created by: <%= article.user.username %>,
            <%= time_ago_in_words(article.created_at) %> ago,
            last updated: <%= time_ago_in_words(article.updated_at) %> ago
          </p>
        </div>
        <div class="text-center">
          <%= link_to "READ MORE", article_path(article) %>
        </div>
        <div class="article-actions">
          <% if user_signed_in? %>
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<p>
  <%= render 'shared/error_messages', resource: @article %>
</p>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-6">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-6">
          <%= f.cktext_area :description, ckeditor: {toolbar: 'mailedit'}, rows: 10, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-large' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center">Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>

<%= render 'article', resources: @articles %>

<nav aria-label="...">
  <ul class="pager">
    <li class="previous <%= @page == 0 ? 'hidden' : '' %>">
      <%= link_to_if @page > 0, "<< Previous", articles_path(page: @page - 1) %>
    </li>

    <li class="next">
      <%= link_to "Next >>", articles_path(page: @page + 1) %>
    </li>
  </ul>
</nav>

app/views/articles/new.html.erb
<h1 class="text-center">Create an Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <h4 class="center"><strong>Description:</strong></h4>
  <hr>
  <%= raw(@article.description).html_safe %>

  <ul class="listing">
    <div class="row">
      <div class="col-md-2">
        <li>
          <%= link_to gravatar_for(@article.user, size: 15), profile_path(@article.user) %>
          <%= link_to @article.user.username, profile_path(@article.user) %>
          <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
        </li>
      </div>
    </div>
  </ul>

  <% if user_signed_in? %>
    <%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %> |
    <%= link_to 'Back', articles_path, class: "btn btn-xs btn-success" %> |
    <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Create Article", new_article_path if user_signed_in? %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'My profile', profile_path(current_user) %></li>
          <li><%= link_to 'Users', profiles_path(@users) %></li>
          <li><%= link_to current_user.email, edit_user_registration_path %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SittmeBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>

    <%= render 'shared/messages' %>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1 class="text-center">About Blog</h1>

<div class="row">
  <div class="col-xs-12 text-center">
    <%= link_to 'Welcome page', root_path %>
  </div>
  <div class="col-xs-12 text-center">
    <h3>Cursor Pagination: Get user's data in json format</h3>

    <%= form_tag json_data_path, method: :get do -%>
      <%= number_field_tag 'cursor', nil, min: 0, :class => 'json_data' %>
      <%= submit_tag 'Request!' %>
    <% end %>
  </div>
</div>

app/views/pages/welcome.html.erb
<h1 class="text-center">Welcome to Blog</h1>

<div class="row">
  <div class="col-xs-12 text-center">
    <%= link_to 'About', about_path %>
  </div>
</div>

app/views/profiles/index.html.erb
<h1 align="center">All Users</h1>

<div align="center">
  <% @users.each do |user| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(user), profile_path(user) %></li>
          <li class="article-title"><%= link_to user.username, profile_path(user) %></li>
          <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
        </div>
      </div>
    </ul>
  <% end %>
</div>

<nav aria-label="...">
  <ul class="pager">
    <li class="previous <%= @page == 0 ? 'hidden' : '' %>">
      <%= link_to_if @page > 0, "<< Previous", profiles_path(page: @page - 1) %>
    </li>

    <li class="next">
      <%= link_to "Next >>", profiles_path(page: @page + 1) %>
    </li>
  </ul>
</nav>

app/views/profiles/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-2 center">
    <%= gravatar_for @user, size: 30 %>
  </div>
</div>
<h4 align="center">
  <%= @user.username %>'s
  <%= pluralize(@user.articles.count, "article") if @user.articles %>
</h4>
<%= render 'articles/article', resources: @user.articles.on_created_at %>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(resource.errors.count, "error") %>
            prohibited this article from being saved:
          </h2>
        <div class="panel-body">
          <ul>
            <% resource.errors.full_messages.each do |msg|%>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    </div>
  </div>
<% end %>

app/views/shared/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>